### ISSUE TITLE
[ToDo] Rework path resolution

### ISSUE THREAD

**Issue by MaxDall** [flairNLP/fundus#164]
As @dobbersc pointed out in #148 the current resolution comes with some problems. To keep an implementation using absolute paths rather than relatives I would rework the current one as follows.

- [ ] Create a fixed root anchor as a variable called `root` referencing the absolute path to the project root directory.
- [ ] Change all existing paths to be relative to this anchor. 

Update:
@dobbersc pointed out in #148 that there wouldn't be any difference in using `pathlib` over `os` beside the advantages of the former and thus proposed to use `pathlib` instead of `os`.

- [ ] Use `pathlib` instead of `os`.
