### ISSUE TITLE
[TODO] Adjust  docs after `ProxyParser` PR is merged

### ISSUE THREAD

**Issue by MaxDall** [flairNLP/fundus#198]
- [x] Open TODOs in existing docs
- [x] Add #187 
- [x] ~~Add class graph for sitemaps~~
- [x] Add documentation for #182 
- [x] Add documentation for #183
