### ISSUE TITLE
[Todo] Finish the migration to the new parser spec format 

### ISSUE THREAD

**Issue by Weyaaron** [flairNLP/fundus#204]
There are some quirks left after #201 has taken place:

- [ ] Update the documentation
- [ ] Rework/Simplify the Sitemap vs Newsmap Situation 
- [ ] Explain what the Sitemap Parameters do
