### ISSUE TITLE
Quality control for parser test cases.

### ISSUE THREAD

**Issue by MaxDall** [flairNLP/fundus#354]
@dobbersc pointed out that there are some obvious errors in the current test cases, especially when looking at the plaintext #338 
This issue is a checklist to go through all test cases and write down anything weird that's present in the test cases.

Update: 22.02
I went through every JSON. Now, the checkbox is indicating if the parser still needs a fix.

at
- [x] ORF

de
- [x] Die Welt:
- [x] Mitteldeutscher Rundfunk (MDR): `Image captions included in the plain text; Author byline at the end` #370 
- [x] Frankfurter Allgemeine Zeitung
- [x] Focus Online: `JS included in the plain text` #382 
- [x] Münchner Merkur
- [x] Süddeutsche Zeitung
- [x] Spiegel Online:
- [x] Die Zeit: `author byline at end of article with dpa` #371 
- [x] Berliner Zeitung: `Duplicate nodes for summary/paragraphs, headline/paragraphs, there was a copy past error with 4d29dcc on the summary selector, this div[data-testid=article-header] > p is the correct one` #372 
- [x] Tagesschau
- [x] Deutsche Welle
- [x] Stern
- [x] N-Tv
- [x] Norddeutscher Rundfunk (NDR): `author included in article text` #373 
- [x] Die Tageszeitung (taz)
- [x] Bild
- [x] Westdeutsche Allgemeine Zeitung (WAZ)
- [x] Braunschweiger Zeitung
- [x] Business Insider: `couldn't load entire text because of privacy restrictions` #376 

fr
- [x] Le Monde: `Selectors for summary and subheadlines are missing although given in the article.` #374 

na
- [x] The Namibian: `summary is missing.` #363 

uk
- [x] The Guardian: `Bad test case` #375 
- [x] The Independent
- [x] The Telegraph: `subheadlines missing` #377
- [ ] i: `change test case with https://inews.co.uk/culture/television/women-took-over-tv-detective-drama-2846727`

us
- [x] Associated Press News
- [x] CNBC: `related content included in the plaintext` #366 
- [x] The Intercept
- [x] The Gateway Pundit: `Image captions included; related content` #367 
- [x] Fox News: `related content included` #368 
- [x] The Nation: `JS included in the V1 test case, V2 bot fully extracted, only the first 6 out of 15 paragraphs` #385 
- [x] ~~World Truth~~
- [x] The Washington Free Beacon: `There is a summary that could be parsed from the HTML` #380 
- [x] The Washington Times:  
- [x] The New Yorker: `summary selector not working` #379
- [x] Reuters:
- [x] Occupy Democrats:  `first paragraph seems to be a summary` #381 
- [x] Los Angeles Times: `subheadlines missing h3[class*=story-title]` #378
