### ISSUE TITLE
Example project: Corpus of political bias

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/fundus#54]
It would be great to add some crawlers for English-language news to the library (once the guidelines are finalized). 

For another research project on detecting political bias and reliability, we require crawlers for the following 12 sources:

- [x] AP News *(Assigned: @dobbersc)*
- [x] Reuters *(Assigned: @dobbersc PR open #179)*
- [x] CNBC *(Assigned: @dobbersc)*
- [x] The Nation *(Assigned: @Weyaaron PR open #160)*
- [x] The Intercept *(Assigned: @dobbersc)*
- [x] The New Yorker *(Assigned: @dobbersc PR open #176)*
- [x] Fox News *(Assigned: @Weyaaron)*
- [x] The Washington Free Beacon *(Assigned: @Weyaaron)*
- [x] Washington Times *(Assigned: @Weyaaron)*
- [x] Occupy Democrats *(Assigned: @dobbersc paused until #178 is closed)*
- [x] World Truth TV *(Assigned: @Weyaaron)*
- [x] The Gateway Pundit *(Assigned: @dobbersc)*

**Comment by lukasgarbas** [comment]
@MaxDall I looked at the data, here are some statistics:

```
APNEWS num articles: 2540
REUTERS num articles: 2800
CNBC num articles: 2006
THENATION num articles: 1944
INTERCEPT num articles: 0
NEWYORKER num articles: 2160
FOXNEWS num articles: 2830
FREEBEACON num articles: 42
WASHINGTONTIMES num articles: 2829
WORLDTRUTH num articles: 10
THEGATEWAYPUNDIT num articles: 2825
```

It would be good to have more articles for The Intercept, Freebeacon and Worldtruth.

I also looked at the quality of extracted text and found javascript code in some of the articles. Probably some improvements for specific parsers could be made. I will open a new issue for that with more details.
